#cloud-config
packages:
  - fail2ban
  - ufw
package_update: true
package_upgrade: true
runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow OpenSSH
  - wget https://github.com/Heclalava/blockpublictorrent-iptables/raw/main/bt.sh
  - chmod +x bt.sh && bash bt.sh
  - ufw deny out from any to 10.0.0.0/8
  - ufw deny out from any to 172.16.0.0/12
  - ufw deny out from any to 192.168.0.0/16
  - ufw deny out from any to 100.64.0.0/10
  - ufw deny out from any to 141.101.78.0/23
  - ufw deny out from any to 173.245.48.0/20
  - ufw deny out from any to 192.0.2.0/24
  - iptables -A OUTPUT -p tcp -s 0/0 -d 10.0.0.0/8 -j DROP
  - iptables -A OUTPUT -p tcp -s 0/0 -d 172.16.0.0/12 -j DROP
  - iptables -A OUTPUT -p tcp -s 0/0 -d 192.168.0.0/16 -j DROP
  - iptables -A OUTPUT -p tcp -s 0/0 -d 100.64.0.0/10 -j DROP
  - iptables -A OUTPUT -p udp -s 0/0 -d 10.0.0.0/8 -j DROP
  - iptables -A OUTPUT -p udp -s 0/0 -d 172.16.0.0/12 -j DROP
  - iptables -A OUTPUT -p udp -s 0/0 -d 192.168.0.0/16 -j DROP
  - iptables -A OUTPUT -p udp -s 0/0 -d 100.64.0.0/10 -j DROP
  - iptables -A OUTPUT -p tcp -s 0/0 -d 141.101.78.0/23 -j DROP
  - iptables -A OUTPUT -p tcp -s 0/0 -d 173.245.48.0/20 -j DROP
  - iptables -A OUTPUT -p tcp -s 0/0 -d 192.0.2.0/24 -j DROP
  - iptables -A OUTPUT -o eth0 -d 169.254.0.0/24 -j DROP
  - iptables -A OUTPUT -o eth0 -d 0.0.0.0/8 -j DROP
  - iptables -A OUTPUT -o eth0 -d 127.0.0.0/8 -j DROP
  - iptables -A OUTPUT -o eth0 -d 169.254.0.0/16 -j DROP
  - iptables -A OUTPUT -o eth0 -d 192.0.2.0/24 -j DROP
  - iptables -A OUTPUT -o eth0 -d 198.18.0.0/15 -j DROP
  - iptables -A OUTPUT -o eth0 -d 224.0.0.0/4 -j DROP
  - iptables -A OUTPUT -o eth0 -d 240.0.0.0/4 -j DROP
  - iptables -A OUTPUT -o eth0 -d 203.0.113.0/24 -j DROP 
  - iptables -A OUTPUT -o eth0 -d 224.0.0.0/3 -j DROP 
  - iptables -A OUTPUT -o eth0 -d 198.51.100.0/24 -j DROP 
  - iptables -A OUTPUT -o eth0 -d 192.88.99.0/24 -j DROP 
  - iptables -A OUTPUT -o eth0 -d 192.0.0.0/24 -j DROP
  - iptables -A OUTPUT -o eth0 -d 223.202.0.0/16 -j DROP
  - iptables -A OUTPUT -o eth0 -d 194.5.192.0/19 -j DROP
  - iptables -A OUTPUT -o eth0 -d 209.237.192.0/18 -j DROP
  - iptables -A OUTPUT -o eth0 -d 169.254.0.0/16 -j DROP
  - iptables-save
  - ufw allow 22
  - ufw enable
  - reboot

  
